name: super_paging
homepage: https://github.com/xsahil03x/super_paging
description: Add pagination or load more functionality to your flutter list view with ease.
version: 1.0.0
repository: https://github.com/xsahil03x/super_paging
issue_tracker: https://github.com/xsahil03x/super_paging/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  freezed_annotation: ^2.4.1
  cancellation_token: ^2.0.1
  logging: ^1.2.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

topics:
  - pagination
  - infinite-scroll
  - load-more
  - paging3
  - endless-scroll

screenshots:
  - description: 'Super Paging Demo'
    path: asset/package_demo.gif